kind: pipeline
name: default

steps:
- name: publish
  image: python:3.7-alpine
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
  commands:
  - apk add --update nodejs-npm
  - npm install -g serverless
  - serverless deploy

when:
  event:
  - push
  branch:
  - master
