kind: pipeline
name: default

steps:
  - name: publish
    image: python:3.7-alpine
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      TELEGRAM_TOKEN:
        from_secret: TELEGRAM_TOKEN
    volumes:
      - name: npm
        path: /drone/src/node_modules
      - name: pip
        path: /.pip
    commands:
      - pip install --cache-dir=/.pip flake8 flake8-import-order
      - flake8
      - apk add --update nodejs-npm
      - npm install
      # - $(npm bin)/serverless deploy
      - $(npm bin)/serverless deploy function -f bot

volumes:
  - name: npm
    host:
      path: /drone/npm
  - name: pip
    host:
      path: /drone/pip

when:
  event:
    - push
  branch:
    - master
