kind: pipeline
name: default

steps:
- name: publish
  image: node:11.11.0
  volumes:
  - name: npm
    path: /drone/src/node_modules
  commands:
  - apt-get update && apt-get install -y python3.6
  - npm install -g serverless
  - npm install
  - serverless deploy

volumes:
- name: npm
  host:
    path: /drone/npm

when:
  event:
  - push
  branch:
  - master
