service: botler

provider:
  name: aws
  runtime: python3.6
  region: ap-southeast-1
  memorySize: 128
  timeout: 10
  versionFunctions: false
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}

functions:
  bot:
    handler: handler.bot
    events:
      - http:
          path: bot
          method: post
          cors: true
