service: botler

provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-1
  memorySize: 256
  timeout: 10
  versionFunctions: false
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}

functions:
  bot:
    handler: src.handler.bot
    events:
      - http:
          path: bot
          method: post
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
